<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tb_caleg_model extends CI_Model
{

    public $table = 'tb_caleg';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function get_dapil(){
        $this->db->order_by('id','ASC');
        $tb_dapil = $this->db->get('tb_dapil');
        return $tb_dapil->result_array();
    }
    
    function get_partai(){
        $this->db->order_by('id','ASC');
        $tb_partai = $this->db->get('tb_partai');
        return $tb_partai->result_array();
    }


    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_dapil', $q);
	$this->db->or_like('id_partai', $q);
	$this->db->or_like('no_urut', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('alamat', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_dapil', $q);
	$this->db->or_like('id_partai', $q);
	$this->db->or_like('no_urut', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('alamat', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tb_caleg_model.php */
/* Location: ./application/models/Tb_caleg_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-08-29 05:18:14 */
/* http://harviacode.com */