<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Users_model extends CI_Model
{

    public $table = 'users';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function get_dapil(){
        $this->db->order_by('id','ASC');
        $dapil = $this->db->get('tb_dapil');
        return $dapil->result_array();
    }

    function get_kecamatan($where) {
            $table = 'tb_kecamatan';
            $this->db->where($where);
            $query=$this->db->get($table);
            return $query;
    }

    function get_kelurahan($where) {
            $table = 'tb_kelurahan';
            $this->db->where($where);
            $query=$this->db->get($table);
            return $query;
    }

    function get_tps($where) {
            $table = 'tb_tps';
            $this->db->where($where);
            $query=$this->db->get($table);
            return $query;
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
    $this->db->or_like('id_dapil', $q);
    $this->db->or_like('id_kecamatan', $q);
    $this->db->or_like('id_kelurahan', $q);
    $this->db->or_like('id_tps', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('pekerjaan', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('level', $q);
	$this->db->or_like('aktif', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
    $this->db->or_like('id_dapil', $q);
    $this->db->or_like('id_kecamatan', $q);
    $this->db->or_like('id_kelurahan', $q);
    $this->db->or_like('id_tps', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('pekerjaan', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('level', $q);
	$this->db->or_like('aktif', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Users_model.php */
/* Location: ./application/models/Users_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-04 19:27:38 */
/* http://harviacode.com */